 SELECT reg_ans, SUM(VL_SALDO_FINAL) FROM demonstracoes_contabeis 
 	WHERE descricao = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR '
 		AND data >= '2021-07-01'
 	GROUP BY reg_ans
 	ORDER BY SUM(VL_SALDO_FINAL) DESC
 	LIMIT 10;


 SELECT reg_ans, SUM(VL_SALDO_FINAL) FROM demonstracoes_contabeis 
 	WHERE descricao = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR '
 		AND data >= '2020-07-01'
 	GROUP BY reg_ans
 	ORDER BY SUM(VL_SALDO_FINAL) DESC
 	LIMIT 10;